spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ToDoApp;
    username: sa
    password: admin
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  liquibase:
    change-log: classpath:db/liquibase.xml
    enabled: true
  jpa:
    show-sql: true